### ISSUE TITLE
/Arduino/libraries/uNavINS/uNavINS.h:144:5: error: 'elapsedMicros' does not name a type

### ISSUE THREAD

**Issue by Robokishan** [bolderflight/uNavINS#2]
just included it in the blank sketch to make sure it compiles because it does not compile in platformio

//This is from arduino IDE
#include "uNavINS.h"
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}

**Comment by Robokishan** [comment]
Sorry, i was compiling for stm32 can you port it to working for stm32 because teensy is not the popular on drone side its very much needy library but doesn't support main flight controllers just add the stm32 support appreciate your efforts in to making this. great work!!1

**Comment by flybrianfly** [comment]
I plan on updating this and the AHRS code in the future. They're both "beta" releases and not as well coded or documented for wide consumption. Apparently, I also need to update to Arduino 1.5 library format. It'll probably be several months before I get to it. In the mean time, you could pull this file and include it to fix your error:
https://github.com/PaulStoffregen/cores/blob/master/teensy3/elapsedMillis.h

If you want to do a pull request, I can merge it.

**Comment by Robokishan** [comment]
Thanks I will try for sure.

**Comment by Robokishan** [comment]
.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/4.8.3/../../../../arm-none-eabi/bin/ld: .pioenvs/genericSTM32F103C8/firmware.elf section `.text' will not fit in region `rom'

.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/4.8.3/../../../../arm-none-eabi/bin/ld: region `rom' overflowed by 60128 bytes

collect2: error: ld returned 1 exit status

seems like stm32f103c is not working properly also tried to compile with arduino but not working
